# App name (unique to your Fly.io account)
app = "sparkquiz-demo"

# Primary region for deployment (choose one close to you or your users)
primary_region = "iad"

# Build configuration
[build]
  builder = "docker"

# HTTP service configuration
[http_service]
  internal_port = 8080  # Port your app listens on (matches gunicorn in Dockerfile)
  force_https = true    # Redirect HTTP to HTTPS
  auto_stop_machines = false  # Keep the app running (no auto-stop)
  auto_start_machines = true  # Start the app on demand
  min_machines_running = 1    # Keep at least 1 instance running

# Environment variables (optional, since secrets are set separately)
[env]
  FLASK_ENV = "production"

# Static file configuration
[[statics]]
  guest_path = "/app/static"  # Path in the Docker container where static files live
  url_prefix = "/static"      # URL path to access static files (e.g., /static/css/style.css)
